apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: message-management
  name: message-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-management
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: message-management
    spec:
      containers:
      - image: harbor.test.com/aiops-nx/message_mgnt:dev
        name: message-management
        imagePullPolicy: Always
        volumeMounts:
        - name: config
          mountPath: /etc/nxyw_message/foreign_url.ini
          subPath: foreign_url.ini
        - name: config
          mountPath: /usr/src/app/settings.yaml
          subPath: settings.yaml
        - name: config
          mountPath: /etc/nxyw_message/dbConnection.ini
          subPath: dbConnection.ini
        ports:
        - containerPort: 8084
          protocol: TCP
        resources: {}
      volumes:
      - name: config
        configMap:
          name: message-mgnt
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: message-management
  name: message-management
spec:
  ports:
  - port: 8084
    protocol: TCP
    targetPort: 8084
  selector:
    app: message-management
